### ISSUE TITLE
create graphql query for currentContenders

### ISSUE THREAD

**Issue by the-color-bliu** [Cappua/cappua-be#29]
- [ ] create graphql query for currentContenders to return info for top three rated verses; ordered by votes; grouped by month
- [ ] create type for currentContenders

**request:**
query currentContenders {
 id
 path
 title
 user { userType }
 votes { voteType }
}

**response**
{

 "data": [
 {
    "id": <integer>
    "path": <string>,
    "title": <string>,
    "description": <string>,
    "user": {
     "id": <integer>
        "name": <string>,
           "image": <string>
   }
          "votes": {
    "id": <integer>
    }
    }
 \\ 2 more verse hashes like this ^
 ]
}

**Comment by ETBassist** [comment]
Should get top three rated verses; ordered by votes, grouped by month.
